/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Joko Prasetyo Utomo
 */
public class gajiKY extends javax.swing.JFrame {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    String oldId = null;
    
private void dataTable() {
    Object[] Baris = {"Id Karyawan", "Nama Karyawan", "Jabatan", "Gaji Pokok", "Tanggal"};
    tabmode = new DefaultTableModel(null, Baris);
    jTable1.setModel(tabmode);
    
    String sql = "SELECT a.nik, b.namaKaryawan, a.jabatan, a.gajiKotor, a.tgl " +
                 "FROM gaji a " +
                 "JOIN dataKaryawan b ON b.nik = a.nik";
    
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        while (hasil.next()) {
            String idnik = hasil.getString("nik");
            String nama = hasil.getString("namaKaryawan");
            String jabat = hasil.getString("jabatan");
            String kotor = hasil.getString("gajiKotor");
            Date tanggal = hasil.getDate("tgl"); // Date type
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(tanggal); // Format Date to String
            String[] data = {idnik, nama, jabat, kotor, tgl};
            tabmode.addRow(data);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}

    protected void kosong(){
    nama.setText("");
    boxNik.setSelectedIndex(0);
    boxJabatan.setSelectedIndex(0);
    tgl.setCalendar(null);
 
    }
    /**
     * Creates new form gajiKY
     */
    public gajiKY() {
        initComponents();
        setIdKaryawan();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dataTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtnik = new javax.swing.JLabel();
        boxNik = new javax.swing.JComboBox<>();
        txtnama = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JLabel();
        boxJabatan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 160, 570, 390));

        txtnik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnik.setForeground(new java.awt.Color(255, 255, 255));
        txtnik.setText("Id Karyawan");
        jPanel1.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        boxNik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNikActionPerformed(evt);
            }
        });
        jPanel1.add(boxNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, -1));

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setText("Nama Karyawan");
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        txtjabatan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtjabatan.setForeground(new java.awt.Color(255, 255, 255));
        txtjabatan.setText("Jabatan");
        jPanel1.add(txtjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        boxJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrasi", "Marketing", "Direktur", "Satpam", "Staff Teknik", "Personalia" }));
        jPanel1.add(boxJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 170, -1));

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 70, -1));

        update.setText("Ubah");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 70, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/back(2).png"))); // NOI18N
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bggawal.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1390, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
try {
    String sql = "INSERT INTO gaji (nik, namaKaryawan, jabatan, gajiKotor, tgl) VALUES (?, ?, ?, ?, ?)";

    PreparedStatement stat = conn.prepareStatement(sql);
    stat.setString(1, boxNik.getSelectedItem().toString());
    stat.setString(2, nama.getText());
    stat.setString(3, boxJabatan.getSelectedItem().toString());
    
    String selectedValue = boxJabatan.getSelectedItem().toString();
    double jumlah = 0.0;
    
    if (selectedValue.equals("Administrasi")) {
        jumlah = 4000000;
    } else if (selectedValue.equals("Marketing")) {
        jumlah = 3500000;
    } else if (selectedValue.equals("Direktur")) {
        jumlah = 8000000;
    } else if (selectedValue.equals("Satpam")) {
        jumlah = 2000000;
    } else if (selectedValue.equals("Staff Teknik")) {
        jumlah = 6000000;
    } else if (selectedValue.equals("Personalia")) {
        jumlah = 5500000;
    }

    // Mengatur nilai gaji pada JTextField gaji
    
    
    stat.setDouble(4, jumlah);
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(tgl.getDate());
    stat.setString(5, tanggal);

    stat.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
    kosong();
    nama.requestFocus();
    dataTable();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
}

    }//GEN-LAST:event_saveActionPerformed

    private void boxNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNikActionPerformed
        // TODO add your handling code here:
  String sql = "SELECT * FROM dataKaryawan WHERE nik = ?";

    try (PreparedStatement stat = conn.prepareStatement(sql)) {
        stat.setString(1, boxNik.getSelectedItem().toString());
        try (ResultSet hasil = stat.executeQuery()) {
            while (hasil.next()) {
                nama.setText(hasil.getString("namaKaryawan"));
                boxJabatan.setSelectedItem(hasil.getString("jabatan"));
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    
    }//GEN-LAST:event_boxNikActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from gaji where nik ='"+boxNik.getSelectedItem()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                nama.requestFocus();
                dataTable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
 try {
        String sql = "UPDATE gaji SET namaKaryawan=?, jabatan=?, gajiKotor=?, tgl=? WHERE nik=?";
        PreparedStatement stat = conn.prepareStatement(sql);
        
        stat.setString(1, nama.getText());
        stat.setString(2, boxJabatan.getSelectedItem().toString());

        String selectedValue = boxJabatan.getSelectedItem().toString();
        double jumlah = 0.0;
        
        if (selectedValue.equals("Administrasi")) {
            jumlah = 4000000;
        } else if (selectedValue.equals("Marketing")) {
            jumlah = 3500000;
        } else if (selectedValue.equals("Direktur")) {
            jumlah = 8000000;
        } else if (selectedValue.equals("Satpam")) {
            jumlah = 2000000;
        } else if (selectedValue.equals("Staff Teknik")) {
            jumlah = 6000000;
        } else if (selectedValue.equals("Personalia")) {
            jumlah = 5500000;
        }
        stat.setDouble(3, jumlah);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate());
        stat.setString(4, tanggal);
        stat.setString(5, boxNik.getSelectedItem().toString());

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        kosong();
        nama.requestFocus();
        dataTable();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Diubah: " + e.getMessage());
    }
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    int bar = jTable1.getSelectedRow();
    String a = tabmode.getValueAt(bar, 0).toString();
    String b = tabmode.getValueAt(bar, 1).toString();
    String c = tabmode.getValueAt(bar, 2).toString();
    String d = tabmode.getValueAt(bar, 3).toString();
    String e = tabmode.getValueAt(bar, 4).toString();
    
    System.out.println(a + " " + b + " " + c + " " + d + " " + e);
    
    this.oldId = a;
    boxNik.setSelectedItem(a);   
    nama.setText(b);      
    boxJabatan.setSelectedItem(c);
    
    double gajiKotor = Double.parseDouble(d);
    if (gajiKotor == 40000000) {
        boxJabatan.setSelectedItem("Administrasi");
    } else if (gajiKotor == 4000000) {
        boxJabatan.setSelectedItem("Marketing");
    } else if (gajiKotor == 3500000) {
        boxJabatan.setSelectedItem("Direktur");
    } else if (gajiKotor == 8000000) {
        boxJabatan.setSelectedItem("Satpam");
    } else if (gajiKotor == 2000000) {
        boxJabatan.setSelectedItem("Staff Teknik");
    } else if (gajiKotor == 5500000) {
        boxJabatan.setSelectedItem("Personalia");
    }
  
    try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date tanggal = dateFormat.parse(e);
        tgl.setDate(tanggal);
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
         home hm=new home();
            hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_kembaliMouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajiKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajiKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajiKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajiKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajiKY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> boxJabatan;
    private javax.swing.JComboBox<String> boxNik;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JLabel txtjabatan;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtnik;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

public void setIdKaryawan() {
    List<String> kyList = new ArrayList<>(); // Objek ArrayList yang akan digunakan untuk menyimpan semua idGap yang diambil dari database.
    String sql = "SELECT nik FROM dataKaryawan"; // Query SQL untuk mengambil semua idGap dari tabel gaptabel

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String nik = hasil.getString("nik");
            kyList.add(nik);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    DefaultComboBoxModel<String> cbnik = new DefaultComboBoxModel<>();
    for (String nik : kyList) {
        cbnik.addElement(nik);
    }

    boxNik.setModel(cbnik);
}}
