/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this tempsslate file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Joko Prasetyo Utomo
 */
public class hitung extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    String oldId = null;

       
private void dataTable() {
    Object[] Baris = {"Id Karyawan", "Nama Karyawan", "Jabatan", "Gaji Pokok", "Insentif", "Pinjaman", "Pajak", "Gaji Bersih", "Tanggal"};
    tabmode = new DefaultTableModel(null, Baris);
    jTable1.setModel(tabmode);
    
    String sql = "SELECT a.nik, b.namaKaryawan, b.jabatan, c.gajiKotor, d.insentif, e.pinjaman, a.pajak, a.gajiBersih, a.tgl " +
                 "FROM hitungan a " +
                 "JOIN dataKaryawan b ON b.nik = a.nik " +
                 "JOIN gaji c ON c.nik = a.nik " +
                 "JOIN lembur d ON d.nik = a.nik " +
                 "JOIN pinjaman e ON e.nik = a.nik";
    
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        while (hasil.next()) {
            String idnik = hasil.getString("nik");
            String nama = hasil.getString("namaKaryawan");
            String jabatan = hasil.getString("jabatan");
            String gajiKotor = hasil.getString("gajiKotor");
            String insentif = hasil.getString("insentif");
            String pinjaman = hasil.getString("pinjaman");
            String pajak = hasil.getString("pajak");
            String gajiBersih = hasil.getString("gajiBersih");                                
            Date tanggal = hasil.getDate("tgl");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(tanggal); // Format Date to String
            String[] data = {idnik, nama, jabatan, gajiKotor, insentif, pinjaman, pajak, gajiBersih, tgl};
            tabmode.addRow(data);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}
  
private void dataHitung() {
    Object[] Baris = {"Id Karyawan", "Nama Karyawan", "Jabatan", "Gaji Pokok", "Insentif", "Pinjaman", "Pajak", "Gaji Bersih", "Tanggal"};
    tabmode = new DefaultTableModel(null, Baris);
    jTable1.setModel(tabmode);
    
    String sql = "SELECT * FROM hitungan";
                
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        
        while (hasil.next()) {
            String idnik = hasil.getString("nik");
            String nama = hasil.getString("namaKaryawan");
            String jabatan = hasil.getString("jabatan");
            String gajiKotor = hasil.getString("gajiKotor");
            String insentif = hasil.getString("insentif");
            String pinjaman = hasil.getString("pinjaman");
            String pajak = hasil.getString("pajak");
            String gajiBersih = hasil.getString("gajiBersih");                                
            Date tanggal = hasil.getDate("tgl");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(tanggal); // Format Date to String
            String[] data = {idnik, nama, jabatan, gajiKotor, insentif, pinjaman, pajak, gajiBersih, tgl};
            tabmode.addRow(data);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}
    protected void kosong(){
    nama.setText("");
    insentif.setText("");
    pinjam.setText("");
    boxNik.setSelectedIndex(0);
    boxkerja.setSelectedIndex(0);
    tgl.setCalendar(null);
 
    }
    public hitung() {
        initComponents();
        setIdKaryawan();
        dataTable();
        setlembur();
        setPinjam();
        dataHitung();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtnik = new javax.swing.JLabel();
        boxNik = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        txtnama = new javax.swing.JLabel();
        boxkerja = new javax.swing.JComboBox<>();
        txtagama1 = new javax.swing.JLabel();
        txtinsen = new javax.swing.JLabel();
        insentif = new javax.swing.JTextField();
        pinjam = new javax.swing.JTextField();
        txtpinjam = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "jabatan", "gaji pokok", "insentif", "pinjaman", "pajak", "gaji bersih", "tgl"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 140, 710, -1));

        txtnik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnik.setForeground(new java.awt.Color(255, 255, 255));
        txtnik.setText("Id Karyawan");
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        boxNik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNikActionPerformed(evt);
            }
        });
        getContentPane().add(boxNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, 30));

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, 30));

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setText("Nama Karyawan");
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        boxkerja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrasi", "Marketing", "Direktur", "Satpam", "Staff Teknik", "Personalia" }));
        getContentPane().add(boxkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, 30));

        txtagama1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtagama1.setForeground(new java.awt.Color(255, 255, 255));
        txtagama1.setText("Jabatan");
        getContentPane().add(txtagama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        txtinsen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtinsen.setForeground(new java.awt.Color(255, 255, 255));
        txtinsen.setText("Insentif");
        getContentPane().add(txtinsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        insentif.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(insentif, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 90, 30));

        pinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 90, 30));

        txtpinjam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpinjam.setForeground(new java.awt.Color(255, 255, 255));
        txtpinjam.setText("Pinjaman");
        getContentPane().add(txtpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 170, -1));

        delete.setText("Hapus");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, 30));

        edit.setText("Ubah");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 100, 30));

        kembali.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/back(2).png"))); // NOI18N
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bghit2ung.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNikActionPerformed
        // TODO add your handling code here:
      String sql1 = "SELECT * FROM dataKaryawan WHERE nik = ?";

    try {
        PreparedStatement stat1 = conn.prepareStatement(sql1);
        stat1.setString(1, boxNik.getSelectedItem().toString());
        ResultSet hasil1 = stat1.executeQuery();

        if (hasil1.next()) {
            nama.setText(hasil1.getString("namaKaryawan"));
            boxkerja.setSelectedItem(hasil1.getString("jabatan"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    // Query to retrieve data from lembur
    String sql2 = "SELECT * FROM lembur WHERE nik = ?";

    try {
        PreparedStatement stat2 = conn.prepareStatement(sql2);
        stat2.setString(1, boxNik.getSelectedItem().toString());
        ResultSet hasil2 = stat2.executeQuery();

        if (hasil2.next()) {
            insentif.setText(hasil2.getString("insentif"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    // Query to retrieve data from pinjaman
    String sql3 = "SELECT * FROM pinjaman WHERE nik = ?";

    try {
        PreparedStatement stat3 = conn.prepareStatement(sql3);
        stat3.setString(1, boxNik.getSelectedItem().toString());
        ResultSet hasil3 = stat3.executeQuery();

        if (hasil3.next()) {
            pinjam.setText(hasil3.getString("pinjaman"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_boxNikActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
  try {
        String sql = "INSERT INTO hitungan (nik, namaKaryawan, jabatan, gajiKotor, insentif, pinjaman, pajak, gajiBersih, tgl) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, boxNik.getSelectedItem().toString());
        stat.setString(2, nama.getText());
        stat.setString(3, boxkerja.getSelectedItem().toString());

        String selectedValue = boxkerja.getSelectedItem().toString();
        double jumlah = 0.0;
        if (selectedValue.equals("Administrasi")) {
            jumlah = 4000000;
        } else if (selectedValue.equals("Marketing")) {
            jumlah = 3500000;
        } else if (selectedValue.equals("Direktur")) {
            jumlah = 8000000;
        } else if (selectedValue.equals("Satpam")) {
            jumlah = 2000000;
        } else if (selectedValue.equals("Staff Teknik")) {
            jumlah = 6000000;
        } else if (selectedValue.equals("Personalia")) {
            jumlah = 5500000;
        }
        
        stat.setDouble(4, jumlah);
        stat.setString(5, insentif.getText());
        stat.setString(6, pinjam.getText());

        double pajak = 0.0;
        if (jumlah == 4000000 || jumlah == 8000000 || jumlah == 6000000 ) {
            pajak = 0.06 * jumlah;
        } else if (jumlah == 2000000 || jumlah == 3000000) {
            pajak = 0.03 * jumlah;
        }
        
        stat.setDouble(7, pajak);
        
        double insentifValue = Double.parseDouble(insentif.getText());
        double pinjamanValue = Double.parseDouble(pinjam.getText());
        double gajiBersih = jumlah - pajak + insentifValue - pinjamanValue;
        
        stat.setDouble(8, gajiBersih);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate());
        stat.setString(9, tanggal);

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        kosong();
        nama.requestFocus();
        dataTable();
        dataHitung();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Format angka tidak valid. " + e.getMessage());
    }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // jtable1 variable baru. jTable1 adalah variable table

    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from hitungan where nik ='"+boxNik.getSelectedItem()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                nama.requestFocus();
                dataTable();
                dataHitung();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     int bar = jTable1.getSelectedRow();
     if (bar != -1) { // Pastikan baris terpilih valid
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString(); 
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString(); 
        String f = tabmode.getValueAt(bar, 8).toString();
        boxNik.setSelectedItem(a);
        nama.setText(b);
        boxkerja.setSelectedItem(c);
        insentif.setText(d);
        pinjam.setText(e);

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date tanggal = dateFormat.parse(f);
            tgl.setDate(tanggal);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
         try {
        String sql = "UPDATE hitungan SET namaKaryawan = ?, jabatan = ?, gajiKotor = ?, insentif = ?, pinjaman = ?, pajak = ?, gajiBersih = ?, tgl = ? WHERE nik = ?";

        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, nama.getText());
        stat.setString(2, boxkerja.getSelectedItem().toString());

        String selectedValue = boxkerja.getSelectedItem().toString();
        double jumlah = 0.0;     
        if (selectedValue.equals("Administrasi")) {
            jumlah = 4000000;
        } else if (selectedValue.equals("Marketing")) {
            jumlah = 3500000;
        } else if (selectedValue.equals("Direktur")) {
            jumlah = 8000000;
        } else if (selectedValue.equals("Satpam")) {
            jumlah = 2000000;
        } else if (selectedValue.equals("Staff Teknik")) {
            jumlah = 6000000;
        } else if (selectedValue.equals("Personalia")) {
            jumlah = 5500000;
        }
        stat.setDouble(3, jumlah);
        stat.setString(4, insentif.getText());
        stat.setString(5, pinjam.getText());

        double pajak = 0.0;
        if (jumlah == 4000000 || jumlah == 8000000 || jumlah == 6000000) {
            pajak = 0.06 * jumlah;
        } else if (jumlah == 2000000 || jumlah == 3000000) {
            pajak = 0.03 * jumlah;
        }
        stat.setDouble(6, pajak);

        double insentifValue = Double.parseDouble(insentif.getText());
        double pinjamanValue = Double.parseDouble(pinjam.getText());
        double gajiBersih = jumlah - pajak + insentifValue - pinjamanValue;
        stat.setDouble(7, gajiBersih);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate());
        stat.setString(8, tanggal);

        stat.setString(9, boxNik.getSelectedItem().toString());

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        kosong();
        nama.requestFocus();
        dataTable();
       
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Diupdate: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Format angka tidak valid. " + e.getMessage());
    }
    }//GEN-LAST:event_editActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
         home hm=new home();
            hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_kembaliMouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> boxNik;
    private javax.swing.JComboBox<String> boxkerja;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField insentif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pinjam;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JLabel txtagama1;
    private javax.swing.JLabel txtinsen;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtnik;
    private javax.swing.JLabel txtpinjam;
    // End of variables declaration//GEN-END:variables
public void setIdKaryawan() {
    List<String> kyList = new ArrayList<>(); // Objek ArrayList yang akan digunakan untuk menyimpan semua idGap yang diambil dari database.
    String sql = "SELECT nik FROM dataKaryawan"; // Query SQL untuk mengambil semua idGap dari tabel gaptabel

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String nik = hasil.getString("nik");
            kyList.add(nik);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    DefaultComboBoxModel<String> cbnik = new DefaultComboBoxModel<>();
    for (String nik : kyList) {
        cbnik.addElement(nik);
    }

    boxNik.setModel(cbnik);
}
public void setlembur() {
    List<String> lemburList = new ArrayList<>(); // Objek ArrayList yang akan digunakan untuk menyimpan semua idGap yang diambil dari database.
    String sql = "SELECT nik FROM lembur"; // Query SQL untuk mengambil semua idGap dari tabel gaptabel

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String nik = hasil.getString("nik");
            lemburList.add(nik);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    DefaultComboBoxModel<String> cbnik = new DefaultComboBoxModel<>();
    for (String nik : lemburList) {
        cbnik.addElement(nik);
    }

    boxNik.setModel(cbnik);
}

public void setPinjam() {
    List<String> pinjamList = new ArrayList<>(); // Objek ArrayList yang akan digunakan untuk menyimpan semua idGap yang diambil dari database.
    String sql = "SELECT nik FROM pinjaman"; // Query SQL untuk mengambil semua idGap dari tabel gaptabel

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String nik = hasil.getString("nik");
            pinjamList.add(nik);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    DefaultComboBoxModel<String> cbnik = new DefaultComboBoxModel<>();
    for (String nik : pinjamList) {
        cbnik.addElement(nik);
    }

    boxNik.setModel(cbnik);
}

}
