/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author Joko Prasetyo Utomo
 */
public class hitungakhir extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    String oldId = null;
    /**
    
     */
    
  private void dataTable() {
    Object[] Baris = {"Id Karyawan", "Nama Karyawan", "Jabatan", "Gaji Pokok", "Status Kerja", "Gaji Bersih", "Tanggal"};
    tabmode = new DefaultTableModel(null, Baris); // Menggunakan variabel instance tabmode
    jTable1.setModel(tabmode);

    String sql = "SELECT a.nik, b.namaKaryawan, b.jabatan, a.gajiPokok, a.statusKerja, a.gajiBersih, a.tgl " +
                 "FROM akhir a " +
                 "JOIN dataKaryawan b ON b.nik = a.nik " +
                 "ORDER BY a.nik ASC";

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String idnik = hasil.getString("nik");
            String nama = hasil.getString("namaKaryawan");
            String jabat = hasil.getString("jabatan");
            String pokok = hasil.getString("gajiPokok");
            String sts = hasil.getString("statusKerja");
            String bersih = hasil.getString("gajiBersih");
            Date tanggal = hasil.getDate("tgl");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(tanggal);
            String[] data = {idnik, nama, jabat, pokok, sts, bersih, tgl};
            tabmode.addRow(data);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}


    protected void kosong(){
    nama.setText("");
    boxNik.setSelectedIndex(0);
    gaji.setText("");
    tgl.setCalendar(null);
 
    }
    public hitungakhir() {
        initComponents();
        setIdKaryawan();
        dataTable();
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        boxNik = new javax.swing.JComboBox<>();
        txtnik = new javax.swing.JLabel();
        txtnama = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        boxkerja = new javax.swing.JComboBox<>();
        txtagama1 = new javax.swing.JLabel();
        txtgaji = new javax.swing.JLabel();
        gaji = new javax.swing.JTextField();
        txtstatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        boxStatus = new javax.swing.JComboBox<>();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 690, -1));

        boxNik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNikActionPerformed(evt);
            }
        });
        getContentPane().add(boxNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 90, 30));

        txtnik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnik.setForeground(new java.awt.Color(255, 255, 255));
        txtnik.setText("Id Karyawan");
        getContentPane().add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setText("Nama Karyawan");
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, 30));

        boxkerja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrasi", "Marketing", "Direktur", "Satpam", "Staff Teknik", "Personalia" }));
        boxkerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxkerjaActionPerformed(evt);
            }
        });
        getContentPane().add(boxkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, 30));

        txtagama1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtagama1.setForeground(new java.awt.Color(255, 255, 255));
        txtagama1.setText("Jabatan");
        getContentPane().add(txtagama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        txtgaji.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtgaji.setForeground(new java.awt.Color(255, 255, 255));
        txtgaji.setText("Gaji Bersih");
        getContentPane().add(txtgaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        gaji.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 90, 30));

        txtstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtstatus.setForeground(new java.awt.Color(255, 255, 255));
        txtstatus.setText("Status Kerja");
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, 30));

        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Pensiun" }));
        getContentPane().add(boxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 90, 30));

        delete.setText("Hapus");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 70, 30));

        edit.setText("Ubah");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 70, -1));

        kembali.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/back(2).png"))); // NOI18N
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 110, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bggaber.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNikActionPerformed
        // TODO add your handling code here:
        String sql1 = "SELECT * FROM dataKaryawan WHERE nik = ?";

        try {
            PreparedStatement stat1 = conn.prepareStatement(sql1);
            stat1.setString(1, boxNik.getSelectedItem().toString());
            ResultSet hasil1 = stat1.executeQuery();

            if (hasil1.next()) {
                nama.setText(hasil1.getString("namaKaryawan"));
                boxkerja.setSelectedItem(hasil1.getString("jabatan"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
      String sql2 = "SELECT * FROM hitungan WHERE nik = ?";

    try {
        PreparedStatement stat2 = conn.prepareStatement(sql2);
        stat2.setString(1, boxNik.getSelectedItem().toString());
        ResultSet hasil2 = stat2.executeQuery();

        if (hasil2.next()) {
            gaji.setText(hasil2.getString("gajiBersih"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_boxNikActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

         try {
        String sql = "INSERT INTO akhir (nik, namaKaryawan, jabatan, gajiPokok, statusKerja, gajiBersih, tgl) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement stat = conn.prepareStatement(sql);
        
        stat.setString(1, boxNik.getSelectedItem().toString());
        stat.setString(2, nama.getText());
        stat.setString(3, boxkerja.getSelectedItem().toString());
        stat.setString(4, gaji.getText());
        stat.setString(5, boxStatus.getSelectedItem().toString());
        
        // Menentukan nilai gajiBersih berdasarkan statusKerja dan gajiPokok
        double gajiPokok = Double.parseDouble(gaji.getText());
        String status = boxStatus.getSelectedItem().toString();
        double bersih = 0.0;
        if (status.equals("Pensiun")) {
            bersih = gajiPokok * 0.6;
        } else if (status.equals("Aktif")) {
            bersih = gajiPokok;
        }
        stat.setDouble(6, bersih);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate());
        stat.setString(7, tanggal);

        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        kosong(); // Metode untuk mengosongkan input setelah penyimpanan
        nama.requestFocus(); // Fokus kembali ke field nama setelah penyimpanan
        dataTable(); // Memuat kembali data setelah penyimpanan

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Format angka tidak valid. " + e.getMessage());
    }
    }//GEN-LAST:event_saveActionPerformed

    private void boxkerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxkerjaActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_boxkerjaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 int bar = jTable1.getSelectedRow();
    if (bar != -1) {
        String a = tabmode.getValueAt(bar, 0).toString(); // Nik
        String b = tabmode.getValueAt(bar, 1).toString(); // Nama Karyawan
        String c = tabmode.getValueAt(bar, 2).toString(); // Jabatan
        String d = tabmode.getValueAt(bar, 3).toString(); // Gaji Pokok
        String e = tabmode.getValueAt(bar, 4).toString(); // Status Kerja
        String f = tabmode.getValueAt(bar, 6).toString(); // Tanggal (kolom ke-7)

        boxNik.setSelectedItem(a);
        nama.setText(b);
        boxkerja.setSelectedItem(c);
        gaji.setText(d);
        boxStatus.setSelectedItem(e);

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date tanggal = dateFormat.parse(f);
            tgl.setDate(tanggal); // Mengatur nilai tanggal di komponen JDateChooser (tgl)
        } catch (ParseException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memparsing tanggal.");
        }
    }
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // jtable1 variable baru. jTable1 adalah variable table
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from akhir where nik ='"+boxNik.getSelectedItem()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                nama.requestFocus();
                dataTable();

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
            try {
        String sql = "UPDATE akhir SET namaKaryawan=?, jabatan=?, gajiPokok=?, statusKerja=?, gajiBersih=?, tgl=? WHERE nik=?";
        PreparedStatement stat = conn.prepareStatement(sql);
        
        stat.setString(1, nama.getText());
        stat.setString(2, boxkerja.getSelectedItem().toString());
        stat.setString(3, gaji.getText());
        stat.setString(4, boxStatus.getSelectedItem().toString());
        
        // Menentukan nilai gajiBersih berdasarkan statusKerja dan gajiPokok
        double gajiPokok = Double.parseDouble(gaji.getText());
        String status = boxStatus.getSelectedItem().toString();
        double bersih = 0.0;
        if (status.equals("Pensiun")) {
            bersih = gajiPokok * 0.6;
        } else if (status.equals("Aktif")) {
            bersih = gajiPokok;
        }
        stat.setDouble(5, bersih);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate());
        stat.setString(6, tanggal);
        
        stat.setString(7, boxNik.getSelectedItem().toString());
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        kosong(); 
        nama.requestFocus(); 
        dataTable();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data Gagal Diupdate: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Format angka tidak valid. " + e.getMessage());
    }
    }//GEN-LAST:event_editActionPerformed

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        home hm=new home();
            hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_kembaliMouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hitungakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hitungakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hitungakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hitungakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hitungakhir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> boxNik;
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JComboBox<String> boxkerja;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField gaji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JLabel txtagama1;
    private javax.swing.JLabel txtgaji;
    private javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtnik;
    private javax.swing.JLabel txtstatus;
    // End of variables declaration//GEN-END:variables
public void setIdKaryawan() {
    List<String> kyList = new ArrayList<>(); // Objek ArrayList yang akan digunakan untuk menyimpan semua idGap yang diambil dari database.
    String sql = "SELECT nik FROM dataKaryawan"; // Query SQL untuk mengambil semua idGap dari tabel gaptabel

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String nik = hasil.getString("nik");
            kyList.add(nik);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    DefaultComboBoxModel<String> cbnik = new DefaultComboBoxModel<>();
    for (String nik : kyList) {
        cbnik.addElement(nik);
    }

    boxNik.setModel(cbnik);
}}
