/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author JOKO PRASETYO UTOMO
 */
public class home extends javax.swing.JFrame {
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //jLabel2.setText(daftar.name+"!");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        karyawn = new javax.swing.JLabel();
        gaji = new javax.swing.JLabel();
        textintensif = new javax.swing.JLabel();
        leadcabang = new javax.swing.JLabel();
        trans = new javax.swing.JLabel();
        dfcabang = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        trans1 = new javax.swing.JLabel();
        bgpicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        karyawn.setBackground(new java.awt.Color(255, 0, 204));
        karyawn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        karyawn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/DATA2.png"))); // NOI18N
        karyawn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        karyawn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawnMouseClicked(evt);
            }
        });
        getContentPane().add(karyawn);
        karyawn.setBounds(380, 180, 160, 100);

        gaji.setBackground(new java.awt.Color(255, 0, 204));
        gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/gajik.png"))); // NOI18N
        gaji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gajiMouseClicked(evt);
            }
        });
        getContentPane().add(gaji);
        gaji.setBounds(610, 180, 150, 110);

        textintensif.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        textintensif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textintensif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/insenti.png"))); // NOI18N
        textintensif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textintensif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textintensifMouseClicked(evt);
            }
        });
        getContentPane().add(textintensif);
        textintensif.setBounds(850, 180, 150, 100);

        leadcabang.setBackground(new java.awt.Color(255, 0, 204));
        leadcabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/pinja.png"))); // NOI18N
        leadcabang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leadcabang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leadcabangMouseClicked(evt);
            }
        });
        getContentPane().add(leadcabang);
        leadcabang.setBounds(380, 330, 150, 110);

        trans.setBackground(new java.awt.Color(255, 0, 204));
        trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bersih.png"))); // NOI18N
        trans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transMouseEntered(evt);
            }
        });
        getContentPane().add(trans);
        trans.setBounds(610, 330, 150, 110);

        dfcabang.setBackground(new java.awt.Color(255, 0, 204));
        dfcabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/22hitung.png"))); // NOI18N
        dfcabang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dfcabang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dfcabangMouseClicked(evt);
            }
        });
        getContentPane().add(dfcabang);
        dfcabang.setBounds(850, 330, 150, 110);

        minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(510, 10, 20, 20);

        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(530, 10, 34, 20);

        kembali.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/back(2).png"))); // NOI18N
        kembali.setContentAreaFilled(false);
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(10, 30, 120, 40);

        trans1.setBackground(new java.awt.Color(255, 0, 204));
        trans1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/lapor.jpg"))); // NOI18N
        trans1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trans1MouseEntered(evt);
            }
        });
        getContentPane().add(trans1);
        trans1.setBounds(610, 490, 150, 100);

        bgpicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/bghome.png"))); // NOI18N
        getContentPane().add(bgpicture);
        bgpicture.setBounds(0, -10, 1370, 790);

        setSize(new java.awt.Dimension(1374, 799));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
       home hm=new home();
            hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_kembaliMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void karyawnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawnMouseClicked
              this.hide();
            Karyawan ky=new Karyawan();
            ky.setVisible(true);
            
// TODO add your handling code here:
    }//GEN-LAST:event_karyawnMouseClicked

    private void dfcabangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dfcabangMouseClicked
            hitung dc=new hitung();
            dc.setVisible(true);

    }//GEN-LAST:event_dfcabangMouseClicked

    private void textintensifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textintensifMouseClicked
        lemburan in=new lemburan();
        in.setVisible(true);
            
    }//GEN-LAST:event_textintensifMouseClicked

    private void gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gajiMouseClicked
        gajiKY gk=new gajiKY();
        gk.setVisible(true);
        
    }//GEN-LAST:event_gajiMouseClicked

    private void leadcabangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leadcabangMouseClicked
        pinjam lc=new pinjam();
        lc.setVisible(true);

    }//GEN-LAST:event_leadcabangMouseClicked

    private void transMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseEntered
               
// TODO add your handling code here:
    }//GEN-LAST:event_transMouseEntered

    private void transMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseClicked
        hitungakhir tr=new hitungakhir();
        tr.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_transMouseClicked

    private void trans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans1MouseClicked
        // TODO add your handling code here:
        report rt=new report();
        rt.setVisible(true);        
    }//GEN-LAST:event_trans1MouseClicked

    private void trans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trans1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_trans1MouseEntered

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.setState(1);

    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgpicture;
    private javax.swing.JLabel dfcabang;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gaji;
    private javax.swing.JLabel karyawn;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel leadcabang;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel textintensif;
    private javax.swing.JLabel trans;
    private javax.swing.JLabel trans1;
    // End of variables declaration//GEN-END:variables
}
